"""add self_reported_posted

Revision ID: 44533a53e136
Revises: 9d4c35d45e6d
Create Date: 2026-03-01 02:46:11.353013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44533a53e136'
down_revision: Union[str, None] = '9d4c35d45e6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('google_review_tracking', sa.Column('self_reported_posted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('google_review_tracking', 'self_reported_posted')
    # ### end Alembic commands ###
