"""add_presentation_mode_to_feedback_sessions

Revision ID: 5a068755fcde
Revises: 44533a53e136
Create Date: 2026-03-01 08:45:51.383600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a068755fcde'
down_revision: Union[str, None] = '44533a53e136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback_sessions', sa.Column('presentation_mode', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback_sessions', 'presentation_mode')
    # ### end Alembic commands ###
